spring:
  datasource:
    url: jdbc:h2:mem:kum;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_FILE=4
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      settings:
        trace: true

logging:
  level:
    h2database: trace
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

archaeodb:
  bulletsCategory: Кулі